language: haskell
cache:
  directories:
    - $HOME/.cabal
ghc:
  - '8.8'
  - '8.6'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libpulse-dev libblas-dev liblapack-dev
script:
  - cabal new-build all
  - cabal new-test all --enable-tests
install: skip
