on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*
name: build
jobs:
  fourmolu:
    name: "Run fourmolu"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Set up and run fourmolu
      run: |
        nix shell nixpkgs#haskellPackages.fourmolu --command fourmolu --mode check .

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8.4','8.10.7','9.0.2','9.2.5','9.4.5']
        os: [ubuntu-latest]
    name: Haskell GHC ${{ matrix.ghc }} cabal + stack
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        id: setup-haskell-build
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
      - name: Install dependencies
        run: sudo apt-get install -y libxml2-utils libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libpulse-dev libblas-dev liblapack-dev libasound2-dev wget
      - name: Cabal update
        run: cabal update
      - name: Cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-build.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ matrix.ghc }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}
      - name: Cabal build dependencies
        run: |
          cabal build all  --enable-tests --only-dependencies
      - name: Cabal build packages
        run: |
          cabal build all --enable-tests
      - name: Cabal test
        run: |
          cabal test all --enable-tests --test-show-details=Always
      - name: Cache stack build artifacts
        uses:  freckle/stack-cache-action@v1.0.1
        with:
          stack-yaml: stack.${{ matrix.ghc }}.yaml
      - name: Stack build and test
        run: |
          stack build --system-ghc --test --stack-yaml stack.${{ matrix.ghc }}.yaml
